version: '3.9'

services:
  api:
    image: ${DOCKER_USERNAME}/family-finance-api
    container_name: family_finance_api
    environment:
      ConnectionStrings__Postgres: "${DB_CONNECTION_STRING}"
      WebBaseUrl: ${WEB_BASE_URL}
      Auth__Key: ${AUTH_KEY}
      Auth__Issuer: ${AUTH_ISSUER}
      Auth__Audience: ${AUTH_AUDIENCE}
      Hash__Pepper: ${HASH_PEPPER}
      Aes__Key: ${AES_KEY}
      Aes__IV: ${AES_IV}
      DefaultUsers__0__Name: ${DEFAULT_USER_0_NAME}
      DefaultUsers__0__Email: $DEFAULT_USER_0_EMAIL}
      DefaultUsers__0__Password: ${DEFAULT_USER_0_PASSWORD}
      DefaultUsers__0__HexTransactionColor: ${DEFAULT_USER_0_TRANSACTION_COLOR}
      DefaultUsers__1__Name: ${DEFAULT_USER_1_NAME}
      DefaultUsers__1__Email: ${DEFAULT_USER_1_EMAIL}
      DefaultUsers__1__Password: ${DEFAULT_USER_1_PASSWORD}
      DefaultUsers__1__HexTransactionColor: ${DEFAULT_USER_1_TRANSACTION_COLOR}
    ports:
      - "8082:8080"
    restart: always
    networks:
      - dev
    deploy:
      resources:
        limits:
          memory: 256m
  
  client:
    image: ${DOCKER_USERNAME}/family-finance-ui
    container_name: family_finance_ui
    depends_on:
      - api
    ports:
      - "8002:80"
    restart: always
    networks:
      - dev
    deploy:
      resources:
        limits:
          memory: 128m

networks:
  dev:
    driver: bridge